### ISSUE TITLE
Migrate to different hosting

### ISSUE THREAD

**Issue by Philippus** [cb372/sbt-explicit-dependencies#102]
On May 1st Bintray will be sunset (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). @cb372 do you already have plans to move sbt-explicit-dependencies somewhere else?

The brownouts mentioned on that page have already started I think.

**Comment by Sciss** [comment]
Cannot find plugin today. Could you publish to maven central, for example?

**Comment by mkurz** [comment]
It seems this library is only hosted on repo.scala-sbt.org which just had a outage: https://github.com/sbt/sbt/issues/7202
I highly recommend publishing a artifacts to maven central via the [sbt-ci-release plugin](https://github.com/sbt/sbt-ci-release) and GitHub actions, see here how this can be done: https://github.com/sbt/sbt-dynver/pull/242

**Comment by guizmaii** [comment]
I still had the issue today on a CI machine 🤔

**Comment by cb372** [comment]
v0.3.1 is now on Maven Central. Sorry it took so long.
