### ISSUE TITLE
Dependencies for Annotations

### ISSUE THREAD

**Issue by diesalbla** [cb372/sbt-explicit-dependencies#20]
On a project we are working on, we have a dependency on the package `jackson-module-scala`, from the FasterXml project. What we use from this dependency is an annotation, `JsonIgnoreProperties`, defined [here](https://github.com/FasterXML/jackson-annotations/blob/ab01a57066d441ed4eda8719808de2f39f094973/src/main/java/com/fasterxml/jackson/annotation/JsonIgnoreProperties.java). We use this annotation in one of the `main` source files. 

```Scala
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_DEFAULT)
case class Fili(
```

However, the `sbt-explicit-dependencies` (as of version "0.2.6") is detecting that as an unused compile dependency.

**Comment by cb372** [comment]
I've tried to reproduce your problem [here](https://github.com/cb372/sbt-explicit-dependencies/tree/reproduce-20/src/sbt-test/basic/jackson-annotation) but it works fine for me. 

Could you have a look at that test case and see if I am misunderstanding your situation?

**Comment by diesalbla** [comment]
The test case is missing one of the two annotations above. On the other hand, in the project I have it was enough to replace the dependency by one to 
```Scala
                "com.fasterxml.jackson.core" % "jackson-annotations" % jacksonVersion,
```
It compiles code and run tests ok now.

**Comment by diesalbla** [comment]
I suppose I can close the issue.
