### ISSUE TITLE
Dependencies in `Provided` scope show up as undeclared

### ISSUE THREAD

**Issue by Philippus** [cb372/sbt-explicit-dependencies#29]
Dependencies that are in `Provided` scope show up as being undeclared. I'd say that is not entirely true. Perhaps they can be removed from the report? Or add some extra commands for that?

I tried it out locally and it seems doable, but not sure if and how you want to go about it.

**Comment by cb372** [comment]
That's a good point. I agree that if you have declared a `libraryDependency` with `Provided` scope, it should be counted as a declared compile dependency.

Would you like to submit a PR for this? I think it should be just a simple change to [isCompileDependency](https://github.com/cb372/sbt-explicit-dependencies/blob/000d72ad7ba92d5274fb80b4641ed8bbc9ee9693/src/main/scala/explicitdeps/Logic.scala#L87) + adding an integration test.
