### ISSUE TITLE
undeclaredDependencies and uncheckedDependencies work incorrect

### ISSUE THREAD

**Issue by rtwnk** [cb372/sbt-explicit-dependencies#63]
Hi, I am using this plugin but found an interesting issue with adding AWS SDK library

```scala
libraryDependencies ++=  Seq(
  "com.amazonaws" % "aws-java-sdk-s3" % Dependencies.AwsSdkVersion
)
```

after the command output is next:

```[warn] logback-scala-commons >>> The project depends on the following libraries for compilation but they are not declared in libraryDependencies:
[warn]  - "com.amazonaws" % "aws-java-sdk-core" % "1.11.683"
[error] (undeclaredCompileDependenciesTest) Failing the build because undeclared dependencies were found
[error] Total time: 0 s, completed May 12, 2020, 4:17:42 PM
```

I am sure it is declared in libraryDependencies. Can you please take a look? B

The current workaround for is to put it there:
```unusedCompileDependenciesFilter -= moduleFilter("com.amazonaws", "aws-java-sdk-s3")```

The second problem is with library 
```
"org.slf4j" % "jul-to-slf4j" % "1.7.6"
```

I was told that it was unused (see the output):
```
sbt:logback-scala-commons> unusedCompileDependenciesTest
[warn] logback-scala-commons >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "org.slf4j" % "jul-to-slf4j" % "1.7.6"
[error] (unusedCompileDependenciesTest) Failing the build because unused dependencies were found
[error] Total time: 0 s, completed May 12, 2020, 4:27:35 PM
```

it is used and the problem was fixed after putting there:
```
unusedCompileDependenciesFilter -= moduleFilter("org.slf4j", "jul-to-slf4j")
``` 

I would be grateful if somebody would take a look

**Comment by cb372** [comment]
For the AWS SDK, it looks like the plugin is working as intended. In `libraryDependencies` you declared a dependency on `aws-java-sdk-s3`. That library introduced a transitive dependency on another library, `aws-java-sdk-core`. Somewhere in your code you are dependency on classes from `aws-java-sdk-core`. Probably `AWSCredentialsProvider` or something like that.

**Comment by cb372** [comment]
Regarding the `jul-to-slf4j` issue, slf4j uses reflection and other magic to discover logging implementations on the classpath, so I'm not surprised the plugin is confused by it. I think using the `moduleFilter` is a reasonable solution here.
