### ISSUE TITLE
Filter scala3-library and scalajs-library by default?

### ISSUE THREAD

**Issue by rossabaker** [cb372/sbt-explicit-dependencies#84]
I'm trying to integrate this plugin with sbt-spiewak, and hitting unused dependencies on the standard libraries not named `scala-library` (namely, `scala3-library` and `scalajs-library`).  The Scala 2 JVM library is [explicitly excluded](https://github.com/cb372/sbt-explicit-dependencies/blob/e64cf7c2ea61cba81c4fa46415076b6c532363d4/src/main/scala/explicitdeps/Logic.scala#L69).  Should Dotty and Scala.js get the same treatment?

See https://github.com/djspiewak/sbt-spiewak/pull/24

**Comment by cb372** [comment]
Agreed. I’d happily accept a PR for this.
